def inicio(): 
    print("vamos uma soma simples?")
    num1 = float(input("digite o primeito numero:"))
#solicite ao usuario um  número e corverte para float 

    num2 = float(input("digite o segundo  numero:"))
#solicite ao usuario um  número e corverte para float 


    soma = num1 + num2
    

    print ("o resultado do calculo de dois numeros que são", num1,  "e" , num2)

    print("para adição é, ", soma )
   


inicio()




















